<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSixxmxp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSixxmxp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSixxmxp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSixxmxp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSixxmxp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Sixxmxp',
    'container.build_id' => 'a7a62330',
    'container.build_time' => 1534765483,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSixxmxp');
